apiVersion: v1
kind: Service
metadata:
  name: rentseeker
spec:
  ports:
    - port: 3000
  selector:
    app: rentseeker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentseeker
spec:
  selector:
    matchLabels:
      app: rentseeker
  replicas: 1
  template:
    metadata:
      labels:
        app: rentseeker
    spec:
      containers:
        - image: marcusbuffett/house-calculator:latest
          name: rentseeker
          ports:
            - containerPort: 3000
              name: rentseeker
      imagePullSecrets:
        - name: docker-hub-secret-key
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rentseeker
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    konghq.com/override: "https-only"
spec:
  tls:
    - secretName: rentseeker-tls
      hosts:
        - rentseeker.app
  rules:
    - host: rentseeker.app
      http: &http_rules
        paths:
          - backend:
              serviceName: rentseeker
              servicePort: 3000
